name: 'pablo_data'
version: '1.0.0'
profile: 'pablo_data'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  pablo_data:  # Nome do projeto
    staging:  # Configuração para models de staging, que será uma view
      +materialized: view
    datamart:  # Configuração para models de datamart, onde está "dm_commodities.sql"
      +materialized: view  # Configurado para view
